
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.AttributedCharacterIterator;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pavilion
 */
public class Main extends javax.swing.JFrame {
    
    JButton m[] = new JButton[25];
    Pistas pistas = new Pistas();
    int pres = 0;
    Pistas.Vertice aux;
    
    public Main() {
        initComponents();
        pistas.AgregarPistas();
        m[1] = btn1;
        m[2] = btn2;
        m[3] = btn3;
        m[4] = btn4;
        m[5] = btn5;
        m[6] = btn6;
        m[7] = btn7;
        m[8] = btn8;
        m[9] = btn9;
        m[10] = btn10;
        m[11] = btn11;
        m[12] = btn12;
        m[13] = btn13;
        m[14] = btn14;
        m[15] = btn15;
        m[16] = btn16;
        m[17] = btn17;
        m[18] = btn18;
        m[19] = btn19;
        m[20] = btn20;
        m[21] = btn21;
        m[22] = btn22;
        m[23] = btn23;
        m[24] = btn24;
        
        for (int i = 1; i <= 24; i++) {
            JButton boton = m[i];
            boton.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    ImageIcon imagen1 = new ImageIcon(getClass().getResource("/Imagenes/tapa.jpg"));
                    Icon trasera = new ImageIcon(imagen1.getImage().getScaledInstance(80, 90, Image.SCALE_DEFAULT));
                    if (boton.getIcon() != null) {
                        boton.setIcon(null);
                    } else {
                        boton.setIcon(trasera);
                    }
                    
                }
            });
        }
        
        Graphics g = preguntas.getGraphics();
        g.drawString("Click para hacer una pista", 200, 65);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn8 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        personaje = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        preguntas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.red);
        setMaximumSize(new java.awt.Dimension(900, 800));
        setMinimumSize(new java.awt.Dimension(856, 800));
        getContentPane().setLayout(null);
        getContentPane().add(btn8);
        btn8.setBounds(680, 210, 90, 100);
        getContentPane().add(btn3);
        btn3.setBounds(230, 210, 90, 100);
        getContentPane().add(btn4);
        btn4.setBounds(320, 210, 90, 100);
        getContentPane().add(btn5);
        btn5.setBounds(410, 210, 90, 100);
        getContentPane().add(btn6);
        btn6.setBounds(500, 210, 90, 100);
        getContentPane().add(btn7);
        btn7.setBounds(590, 210, 90, 100);
        getContentPane().add(btn9);
        btn9.setBounds(50, 310, 90, 100);

        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10);
        btn10.setBounds(140, 310, 90, 100);
        getContentPane().add(btn11);
        btn11.setBounds(230, 310, 90, 100);
        getContentPane().add(btn12);
        btn12.setBounds(320, 310, 90, 100);
        getContentPane().add(btn13);
        btn13.setBounds(410, 310, 90, 100);
        getContentPane().add(btn14);
        btn14.setBounds(500, 310, 90, 100);
        getContentPane().add(btn2);
        btn2.setBounds(140, 210, 90, 100);

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(50, 210, 90, 100);
        getContentPane().add(btn15);
        btn15.setBounds(590, 310, 90, 100);
        getContentPane().add(btn16);
        btn16.setBounds(680, 310, 90, 100);
        getContentPane().add(btn24);
        btn24.setBounds(680, 410, 90, 100);
        getContentPane().add(btn23);
        btn23.setBounds(590, 410, 90, 100);
        getContentPane().add(btn22);
        btn22.setBounds(500, 410, 90, 100);
        getContentPane().add(btn21);
        btn21.setBounds(410, 410, 90, 100);
        getContentPane().add(btn20);
        btn20.setBounds(320, 410, 90, 100);
        getContentPane().add(btn19);
        btn19.setBounds(230, 410, 90, 100);

        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });
        getContentPane().add(btn18);
        btn18.setBounds(140, 410, 90, 100);
        getContentPane().add(btn17);
        btn17.setBounds(50, 410, 90, 100);

        personaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(personaje);
        personaje.setBounds(560, 520, 200, 130);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADIVINA QUIEN");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 10, 370, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 70, 720, 120);

        preguntas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        preguntas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        preguntas.setFont(new java.awt.Font("Source Sans Pro Light", 1, 24)); // NOI18N
        preguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preguntasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                preguntasMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                preguntasMouseReleased(evt);
            }
        });
        getContentPane().add(preguntas);
        preguntas.setBounds(50, 520, 500, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -50, 850, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn18ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void preguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preguntasMouseClicked
        int tam = aux.vertices.size();
        Graphics g = preguntas.getGraphics();
            g.setColor(Color.white);
            g.clearRect(0, 0, 500, 130);
            g.setColor(Color.black);
            tam = (int) (500 / tam);
        int espacio = tam, cont = 0, sw = 0;
        if (pres != 1) {
            Point punto = evt.getPoint();
            int x1 = punto.x;
            aux = aux.vertices.get(x1 / tam);
            if (aux.vertices.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pista enviada");
                sw = 1;
                pres=0;
                aux=pistas.ptr;
            }
        }
        if (sw == 0) {
            tam = aux.vertices.size();
            tam = (int) (500 / tam);
            espacio = tam;
            
            
            for (Pistas.Vertice vertice : aux.vertices) {
                g.drawLine(espacio, 0, espacio, 130);
                g.drawString(vertice.info, ((tam * cont) + (tam / 2)) - 40, 65);
                espacio = espacio + tam;
                cont++;
            }
            pres = 2;
        }
        
    }//GEN-LAST:event_preguntasMouseClicked

    private void preguntasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preguntasMouseReleased

    }//GEN-LAST:event_preguntasMouseReleased

    private void preguntasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preguntasMouseEntered
        if (pres == 0) {
            Graphics g = preguntas.getGraphics();
            g.drawString("Click para hacer una pista", 100, 65);
            aux = pistas.ptr;
            pres = 1;
        }

    }//GEN-LAST:event_preguntasMouseEntered
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel personaje;
    private javax.swing.JPanel preguntas;
    // End of variables declaration//GEN-END:variables
}
